lint:
  actions_ci: false
  files_exist:
    - CODE_OF_CONDUCT.md
    - assets/nf-core-pangbank_logo_light.png
    - docs/images/nf-core-pangbank_logo_light.png
    - docs/images/nf-core-pangbank_logo_dark.png
    - .github/ISSUE_TEMPLATE/config.yml
    - .github/workflows/awstest.yml
    - .github/workflows/awsfulltest.yml
    - conf/test_full.config
    - conf/igenomes.config
  files_unchanged:
    - CODE_OF_CONDUCT.md
    - assets/nf-core-pangbank_logo_light.png
    - docs/images/nf-core-pangbank_logo_light.png
    - docs/images/nf-core-pangbank_logo_dark.png
    - .github/ISSUE_TEMPLATE/bug_report.yml
    - .gitignore
  multiqc_config:
    - report_comment
  nextflow_config:
    - manifest.name
    - manifest.homePage
    - params.input
nf_core_version: 3.2.0
repository_type: pipeline
template:
  author: Jean Mainguy
  description: A pipeline to build a PPanGGoLiN pangenome database from GTDB genomes.
  force: false
  is_nfcore: false
  name: pangbank
  org: labgem
  outdir: .
  skip_features: []
  version: 1.0dev
